### ISSUE TITLE
mmr-cookie name mismatch

### ISSUE THREAD

**Issue by roberi** [Korrd/mapmyfitness-to-strava-migrator#9]
Following the instructions in the [How to use it](https://github.com/Korrd/mapmyfitness-to-strava-migrator?tab=readme-ov-file#how-to-use-it) section:

```python
python migrator.py --mmr_cookie="<session cookie on a string>"
```

 gives me this error:

```terminal
❌ Argument "--mmr-cookie" is missing or empty!
```

Please update the README to use the correct parameter name.

PS. Just like you I need to migrate from MapMyFitness to Strava. Thanks for a great script that makes this migration so much easier!

**Comment by Korrd** [comment]
Thanks for reporting it. Fixed as part of https://github.com/Korrd/mapmyfitness-to-strava-migrator/pull/11
